### ISSUE TITLE
Fix Creating GitHub Release on Package Publish

### ISSUE THREAD

**Issue by masoudmanson** [chanzuckerberg/sci-components#597]
The following Jobs have been added to the release workflow to handle creating GitHub releases on the SDS package publish.

```yml
  # Job 2
  create-version-matrix:
    needs: release
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      # Step 1: Check out the repository code
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: prod

      # Step 2: Create a matrix of package versions and names
      - name: Create Versions Matrix
        id: set-matrix
        run: |
          matrix="["
          for package_json in $(find ./packages -name package.json); do
            version=$(jq -r .version "$package_json")
            name=$(jq -r .name "$package_json")
            matrix="${matrix}{\"name\":\"${name}\", \"version\":\"${version}\"},"
          done
          matrix="${matrix%,}" # Remove trailing comma
          matrix="${matrix}]" # Close the JSON array
          echo "matrix=${matrix}" >> $GITHUB_OUTPUT

  # Job 3
  create-github-release:
    needs: create-version-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cfg: ${{fromJson(needs.create-version-matrix.outputs.matrix)}}
    steps:
      # Step 1: Create a GitHub release for the latest version
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "${{ matrix.cfg.name }}@${{ matrix.cfg.version }}"

```
